### ISSUE TITLE
Setting to automatically resize images before uploading to imgur.

### ISSUE THREAD

**Issue by vincentriemer** [mileswd/mac2imgur#52]
I recently got one of the new iMac retinas and I've encountered a problem that if I take a fullscreen screenshot of the desktop I encounter the 'image must be less than 10MB' error. There should be a way for mac2imgur to resize the image automatically to meet the 10MB requirement so users don't ever have to see that error message.

**Comment by mileswd** [comment]
Will do :+1:

(Should also resolve #50 & #47)

**Comment by mileswd** [comment]
I've just committed the initial implementation of screenshot resizing (019aac2478d8b6c800f6f9cf27a8aa8ec1e24a6b) - unfortunately I have a MacBook Air, which doesn't have a retina display, so I can't test this properly.

Could you give this feature a quick test? Just enable ```Resize screenshots``` in the options menu and it should work :smile:

**Comment by vincentriemer** [comment]
Do you think you can release a beta build for me to test? I don't currently have the dev environment setup to build it myself.

**Comment by mileswd** [comment]
Sure, no problem.

You can download it here: https://www.dropbox.com/s/qlkgwkyidl1rm75/mac2imgur-testing.zip?dl=0

**Comment by vincentriemer** [comment]
Just tested it and I'm still getting the 10MB limit error 

![error message](https://i.imgur.com/4TYshVQ.png)

**Comment by mileswd** [comment]
Hm, could you possibly try this build:

https://www.dropbox.com/s/qlkgwkyidl1rm75/mac2imgur-testing.zip?dl=0

Thanks in advance

**Comment by vincentriemer** [comment]
That did it!

https://i.imgur.com/YFxPW48.png

**Comment by mileswd** [comment]
Awesome! I still have a little tidying to do in regards to screenshot resizing, but I hope to push out an update soon(ish).

On an unrelated note: wow - 5k displays are massive!

**Comment by vincentriemer** [comment]
Yeah it has provided a huge boost to my productivity.

**Comment by mileswd** [comment]
Just pushed out an update including this - however, the feature is not as thoroughly tested as usual. Feel free to direct any problems to a new issue ticket.

Cheers!

**Comment by k-bx** [comment]
Perfect! Thank you.
